const song = {
  id: "2998843",
  title: "Something Just Like This",
  lyrics:
    "[Verse 1: Chris Martin]\nI've been reading books of old\nThe legends and the myths\nAchilles and his gold\nHercules and his gifts\nSpider-Man's control\nAnd Batman with his fists\nAnd clearly I don't see myself upon that list\n\n[Pre-Chorus: Chris Martin]\nBut she said, where d'you wanna go?\nHow much you wanna risk?\nI'm not looking for somebody\nWith some superhuman gifts\nSome superhero\nSome fairytale bliss\nJust something I can turn to\nSomebody I can kiss\nI want something just like this\nDoo-doo-doo, doo-doo-doo\nDoo-doo-doo, doo, doo\nDoo-doo-doo, doo-doo-doo\nOh, I want something just like this\nDoo-doo-doo, doo-doo-doo\nDoo-doo-doo, doo, doo\nDoo-doo-doo, doo-doo-doo\n\n[Chorus: Chris Martin]\nOh, I want something just like this\nI want something just like this\n\n[Verse 2: Chris Martin]\nI've been reading books of old\nThe legends and the myths\nThe testaments they told\nThe moon and its eclipse\nAnd Superman unrolls\nA suit before he lifts\nBut I'm not the kind of person that it fits\n\n[Pre-Chorus: Chris Martin]\nShe said, where d'you wanna go?\nHow much you wanna risk?\nI'm not looking for somebody\nWith some superhuman gifts\nSome superhero\nSome fairytale bliss\nJust something I can turn to\nSomebody I can miss\n\n[Chorus: Chris Martin]\nI want something just like this\nI want something just like this\n\n[Bridge: Chris Martin]\nOh, I want something just like this\nDoo-doo-doo, doo-doo-doo\nDoo-doo-doo, doo, doo\nDoo-doo-doo, doo-doo-doo\nOh, I want something just like this\nDoo-doo-doo, doo-doo-doo\nDoo-doo-doo, doo, doo\nDoo-doo-doo, doo-doo-doo\n\n[Pre-Chorus: Chris Martin]\nWhere d'you wanna go?\nHow much you wanna risk?\nI'm not looking for somebody\nWith some superhuman gifts\nSome superhero\nSome fairytale bliss\nJust something I can turn to\nSomebody I can kiss\nI want something just like this\n\n[Chorus: Chris Martin]\nOh, I want something just like this\nOh, I want something just like this\nOh, I want something just like this",
  media: [
    {
      provider: "youtube",
      start: 0,
      type: "video",
      url: "http://www.youtube.com/watch?v=FM7MFYoylVs",
    },
    {
      native_uri: "spotify:track:1dNIEtp7AY3oDAKCGg2XkH",
      provider: "spotify",
      type: "audio",
      url: "https://open.spotify.com/track/1dNIEtp7AY3oDAKCGg2XkH",
    },
    {
      attribution: "thechainsmokers",
      provider: "soundcloud",
      type: "audio",
      url: "https://soundcloud.com/thechainsmokers/something-just-like-this-1?in=thechainsmokers/sets/memories-do-not-open-1",
    },
  ],
  splitLyrics: [
    "[Verse 1: Chris Martin]",
    "I've been reading books of old",
    "The legends and the myths",
    "Achilles and his gold",
    "Hercules and his gifts",
    "Spider-Man's control",
    "And Batman with his fists",
    "And clearly I don't see myself upon that list",
    "",
    "[Pre-Chorus: Chris Martin]",
    "But she said, where d'you wanna go?",
    "How much you wanna risk?",
    "I'm not looking for somebody",
    "With some superhuman gifts",
    "Some superhero",
    "Some fairytale bliss",
    "Just something I can turn to",
    "Somebody I can kiss",
    "I want something just like this",
    "Doo-doo-doo, doo-doo-doo",
    "Doo-doo-doo, doo, doo",
    "Doo-doo-doo, doo-doo-doo",
    "Oh, I want something just like this",
    "Doo-doo-doo, doo-doo-doo",
    "Doo-doo-doo, doo, doo",
    "Doo-doo-doo, doo-doo-doo",
    "",
    "[Chorus: Chris Martin]",
    "Oh, I want something just like this",
    "I want something just like this",
    "",
    "[Verse 2: Chris Martin]",
    "I've been reading books of old",
    "The legends and the myths",
    "The testaments they told",
    "The moon and its eclipse",
    "And Superman unrolls",
    "A suit before he lifts",
    "But I'm not the kind of person that it fits",
    "",
    "[Pre-Chorus: Chris Martin]",
    "She said, where d'you wanna go?",
    "How much you wanna risk?",
    "I'm not looking for somebody",
    "With some superhuman gifts",
    "Some superhero",
    "Some fairytale bliss",
    "Just something I can turn to",
    "Somebody I can miss",
    "",
    "[Chorus: Chris Martin]",
    "I want something just like this",
    "I want something just like this",
    "",
    "[Bridge: Chris Martin]",
    "Oh, I want something just like this",
    "Doo-doo-doo, doo-doo-doo",
    "Doo-doo-doo, doo, doo",
    "Doo-doo-doo, doo-doo-doo",
    "Oh, I want something just like this",
    "Doo-doo-doo, doo-doo-doo",
    "Doo-doo-doo, doo, doo",
    "Doo-doo-doo, doo-doo-doo",
    "",
    "[Pre-Chorus: Chris Martin]",
    "Where d'you wanna go?",
    "How much you wanna risk?",
    "I'm not looking for somebody",
    "With some superhuman gifts",
    "Some superhero",
    "Some fairytale bliss",
    "Just something I can turn to",
    "Somebody I can kiss",
    "I want something just like this",
    "",
    "[Chorus: Chris Martin]",
    "Oh, I want something just like this",
    "Oh, I want something just like this",
    "Oh, I want something just like this",
  ],
};

module.exports = song;
